# Copyright 2013, Dell
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

barclamp:
  name: "logging"
  parent: "core"
  display: "Logging"
  description: "Log Centralization and Management"
  version: "2.E"
  source_url: "https://github.com/digitalrebar/core"
  license: "Apache 2"
  license_url: "https://github.com/digitalrebar/core/blob/develop/doc/licenses/README.md"



roles:
  - name: logging-server
    jig: chef
    icon: content_paste
    requires:
      - dns-client
    attribs:
      - name: logging_server
        description: "The IP addresses of the server that should get all logging output."
        map: 'rebar/logging/servers'
      - name: logging-external_servers
        description: 'The IP addresses if the external log server we should ship logs to'
        map: 'rebar/logging/external_servers'
        default: []
        schema:
          type: seq
          sequence:
            - type: str
  - name: logging-client
    jig: chef
    icon: create
    flags:
      - implicit
    requires:
      - dns-client
      - logging-server
    wants-attribs:
      - logging_server
      - use-logging

attribs:
  - name: use-logging
    description: 'Whether the node should attempt to use the logging service'
    map: 'rebar/providers/use_logging'
    default: true
    schema:
      type: bool
      required: true
